services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAMESPACE: ${DB_NAMESPACE}
      DB_DATABASE: ${DB_DATABASE}
      DB_URL: ${DB_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      PORT: ${PORT}
      ENVIRONMENT: ${ENVIRONMENT}
      LIVEKIT_URL: ${LIVEKIT_URL}
      LIVEKIT_KEY: ${LIVEKIT_KEY}
      LIVEKIT_SECRET: ${LIVEKIT_SECRET}
      B2_ID: ${B2_ID}
      B2_KEY: ${B2_KEY}
      B2_ENDPOINT: ${B2_ENDPOINT}
      B2_REGION: ${B2_REGION}
      B2_URL: ${B2_URL}
    # ports:
    #   - "8080:8080"
    restart: unless-stopped
