services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAMESPACE: ${DB_NAMESPACE}
      DB_DATABASE: ${DB_DATABASE}
      DB_URL: ${DB_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      PORT: ${PORT}
    # ports:
    #   - "8080:8080"
    restart: unless-stopped
